"""
Central catalog of all tunables for the control plane.

Each entry:
  key, group, type (str|int|bool|secret|list), default, description,
  restart (bool), optional: label, options, simple, placeholder
"""
from __future__ import annotations

from typing import Any

# restart=True means register process should be restarted to apply.
# simple=True shows on the "常用配置" tab by default.
CATALOG: list[dict[str, Any]] = [
    # ── email ──
    {
        "key": "EMAIL_MODE",
        "group": "email",
        "type": "choice",
        "default": "tempmail",
        "label": "邮箱模式",
        "desc": "用哪种方式收验证码",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "tempmail", "label": "免费临时邮箱（零配置）"},
            {"value": "moemail", "label": "MoeMail OpenAPI"},
            {"value": "custom", "label": "自建域名邮箱"},
        ],
    },
    {
        "key": "EMAIL_DOMAIN",
        "group": "email",
        "type": "str",
        "default": "",
        "label": "自建域名",
        "desc": "custom 模式：你的收信域名，如 example.com",
        "restart": True,
        "simple": True,
        "placeholder": "example.com",
    },
    {
        "key": "EMAIL_API",
        "group": "email",
        "type": "str",
        "default": "http://127.0.0.1:8080",
        "label": "自建收信地址",
        "desc": "custom 模式 webhook / 本地邮箱服务",
        "restart": True,
        "simple": True,
    },
    {
        "key": "MOEMAIL_API",
        "group": "email",
        "type": "str",
        "default": "https://moemail.app",
        "label": "MoeMail 地址",
        "desc": "MoeMail 服务 URL",
        "restart": True,
        "simple": True,
    },
    {
        "key": "MOEMAIL_API_KEY",
        "group": "email",
        "type": "secret",
        "default": "",
        "label": "MoeMail API Key",
        "desc": "以 mk_ 开头的密钥",
        "restart": True,
        "simple": True,
        "placeholder": "mk_xxx",
    },
    {
        "key": "MOEMAIL_DOMAIN",
        "group": "email",
        "type": "str",
        "default": "",
        "label": "MoeMail 邮箱域名",
        "desc": "留空则自动选择",
        "restart": True,
        "simple": False,
    },
    {
        "key": "MOEMAIL_EXPIRY_MS",
        "group": "email",
        "type": "int",
        "default": "3600000",
        "label": "MoeMail 有效期",
        "desc": "毫秒，默认 1 小时",
        "restart": True,
        "simple": False,
    },
    {
        "key": "EMAIL_CODE_RESEND_ATTEMPTS",
        "group": "email",
        "type": "int",
        "default": "2",
        "label": "验证码重发次数",
        "desc": "收不到码时最多再发几次",
        "restart": True,
        "simple": False,
    },
    {
        "key": "EMAIL_CODE_RESEND_AFTER_SEC",
        "group": "email",
        "type": "int",
        "default": "35",
        "label": "重发等待秒数",
        "desc": "多久没收到验证码后重发",
        "restart": True,
        "simple": False,
    },
    # ── capacity ──
    {
        "key": "TARGET",
        "group": "capacity",
        "type": "int",
        "default": "0",
        "label": "成功目标数",
        "desc": "成功注册 N 个后自动停止；0=不限",
        "restart": True,
        "simple": True,
    },
    {
        "key": "PHYSICAL_CAP",
        "group": "capacity",
        "type": "int",
        "default": "0",
        "label": "浏览器并发",
        "desc": "同时开几个浏览器任务；0=按 CPU/内存自动",
        "restart": True,
        "simple": True,
    },
    {
        "key": "PHYSICAL_PER_CPU",
        "group": "capacity",
        "type": "int",
        "default": "2",
        "label": "每核并发参考",
        "desc": "自动算并发时每 CPU 核参考值",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PHYSICAL_MEM_MB",
        "group": "capacity",
        "type": "int",
        "default": "512",
        "label": "每任务内存预算",
        "desc": "MB，用于自动估算并发",
        "restart": True,
        "simple": False,
    },
    {
        "key": "MIN_FREE_MEM_MB",
        "group": "capacity",
        "type": "int",
        "default": "500",
        "label": "系统保留内存",
        "desc": "MB，留给系统不要占满",
        "restart": True,
        "simple": False,
    },
    {
        "key": "S_WORKERS",
        "group": "capacity",
        "type": "int",
        "default": "0",
        "label": "Token 工人数",
        "desc": "0=自动",
        "restart": True,
        "simple": False,
    },
    {
        "key": "P_WORKERS",
        "group": "capacity",
        "type": "int",
        "default": "0",
        "label": "邮箱工人数",
        "desc": "0=自动",
        "restart": True,
        "simple": False,
    },
    {
        "key": "C_WORKERS",
        "group": "capacity",
        "type": "int",
        "default": "0",
        "label": "注册工人数",
        "desc": "0=自动",
        "restart": True,
        "simple": False,
    },
    {
        "key": "T_SLOT_CAP",
        "group": "capacity",
        "type": "int",
        "default": "8",
        "label": "Token 缓冲容量",
        "desc": "库存里最多囤多少 token",
        "restart": True,
        "simple": False,
    },
    {
        "key": "Q_SLOT_CAP",
        "group": "capacity",
        "type": "int",
        "default": "8",
        "label": "验证码缓冲容量",
        "desc": "库存里最多囤多少验证码",
        "restart": True,
        "simple": False,
    },
    {
        "key": "Q_PENDING_CAP",
        "group": "capacity",
        "type": "int",
        "default": "12",
        "label": "在途发码上限",
        "desc": "同时等待验证码返回的请求数",
        "restart": True,
        "simple": False,
    },
    {
        "key": "T_TARGET",
        "group": "capacity",
        "type": "int",
        "default": "4",
        "label": "Token 目标水位",
        "desc": "希望库存维持的 token 数量",
        "restart": True,
        "simple": False,
    },
    {
        "key": "Q_TARGET",
        "group": "capacity",
        "type": "int",
        "default": "4",
        "label": "验证码目标水位",
        "desc": "希望库存维持的验证码数量",
        "restart": True,
        "simple": False,
    },
    {
        "key": "P_BATCH_MAX",
        "group": "capacity",
        "type": "int",
        "default": "4",
        "label": "单页最多发码",
        "desc": "同一邮箱页最多连发几次码",
        "restart": True,
        "simple": False,
    },
    {
        "key": "P_SEND_CAP",
        "group": "capacity",
        "type": "int",
        "default": "0",
        "label": "发码并发",
        "desc": "0=不限制",
        "restart": True,
        "simple": False,
    },
    {
        "key": "REGISTER_ENGINE",
        "group": "capacity",
        "type": "choice",
        "default": "protocol",
        "label": "注册引擎",
        "desc": "protocol=Python HTTP 协议（推荐）；go=Go worker；python=浏览器",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "protocol", "label": "协议注册 HTTP（推荐）"},
            {"value": "go", "label": "Go register-worker"},
            {"value": "python", "label": "Python 浏览器"},
        ],
    },
    {
        "key": "GO_REGISTER_WORKERS",
        "group": "capacity",
        "type": "int",
        "default": "8",
        "label": "协议注册并发数",
        "desc": "REGISTER_ENGINE=protocol/go 时的 worker 数",
        "restart": True,
        "simple": True,
    },
    {
        "key": "INVENTORY_ENGINE",
        "group": "export",
        "type": "choice",
        "default": "rust",
        "label": "库存引擎",
        "desc": "合并 CPA/sub2api 包用的引擎",
        "restart": False,
        "simple": True,
        "options": [
            {"value": "rust", "label": "Rust（默认，硬性栈）"},
            {"value": "python", "label": "Python 回退"},
        ],
    },
    {
        "key": "INVENTORY_WORKER_BIN",
        "group": "export",
        "type": "str",
        "default": "",
        "label": "Rust 库存程序路径",
        "desc": "留空用默认 native/inventory-worker/inventory-worker",
        "restart": False,
        "simple": False,
    },
    # ── turnstile ──
    {
        "key": "TURNSTILE_SOLVER",
        "group": "turnstile",
        "type": "choice",
        "default": "hybrid",
        "label": "Turnstile 求解器",
        "desc": "默认 hybrid=新版多语言混合（Go gateway + Rust watchdog + C++ util + Python 浏览器）。旧版 d3vin/theyka 不推荐",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "hybrid", "label": "新版 Hybrid 多语言（Go+Rust+C+++Py，推荐）"},
            {"value": "d3vin", "label": "旧版 D3-vin"},
            {"value": "theyka", "label": "旧版 Theyka"},
            {"value": "local", "label": "本机 local 注入"},
            {"value": "api", "label": "外部 API URL"},
        ],
    },
    {
        "key": "SOLVER_GATEWAY_WORKERS",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "Hybrid 浏览器 worker 数",
        "desc": "auto=按 CPU+可用内存定规模；也可填数字。请求突发进队列",
        "restart": True,
        "simple": True,
        "placeholder": "auto",
    },
    {
        "key": "SOLVER_GATEWAY_WORKERS_MAX",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "Hybrid worker 上限",
        "desc": "auto=按内存档限制；或填数字。防止浏览器开太多 OOM",
        "restart": True,
        "simple": True,
        "placeholder": "auto",
    },
    {
        "key": "SOLVER_WORKER_CONCURRENCY",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "每浏览器异步页数",
        "desc": "auto=少 worker 且内存充足时常为 2，否则 1。也可填数字",
        "restart": True,
        "simple": True,
        "placeholder": "auto",
    },
    {
        "key": "SOLVER_WORKER_PREFETCH",
        "group": "turnstile",
        "type": "bool",
        "default": "1",
        "label": "异步预热浏览器",
        "desc": "worker 启动时预加载 Turnstile 脚本，降低首包延迟",
        "restart": True,
        "simple": False,
    },
    {
        "key": "SOLVER_GATEWAY_QUEUE",
        "group": "turnstile",
        "type": "int",
        "default": "0",
        "label": "任务队列深度",
        "desc": "0=自动 workers×concurrency×16，支持突发异步投递",
        "restart": True,
        "simple": False,
    },
    {
        "key": "SOLVER_WATCHDOG_SOFT_MB",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "Worker 软内存上限 MB",
        "desc": "auto=按主机总内存/可用内存推算；或填数字。超过后回收浏览器",
        "restart": True,
        "simple": True,
        "placeholder": "auto",
    },
    {
        "key": "SOLVER_WATCHDOG_HARD_MB",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "Worker 硬内存上限 MB",
        "desc": "auto=随 soft 推算；或填数字。超过强制重启 worker",
        "restart": True,
        "simple": True,
        "placeholder": "auto",
    },
    {
        "key": "SOLVER_WATCHDOG_INTERVAL_SEC",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "Watchdog 巡检间隔秒",
        "desc": "auto=内存紧时更勤（约 4～12s）；或填数字",
        "restart": True,
        "simple": False,
        "placeholder": "auto",
    },
    {
        "key": "SOLVER_WORKER_MAX_SOLVES",
        "group": "turnstile",
        "type": "str",
        "default": "auto",
        "label": "每浏览器最多求解次数",
        "desc": "auto=按主机内存档（约 5～12）；达次数后重启 Chromium",
        "restart": True,
        "simple": False,
        "placeholder": "auto",
    },
    {
        "key": "TURNSTILE_API_URL",
        "group": "turnstile",
        "type": "str",
        "default": "",
        "label": "Turnstile API 地址",
        "desc": "留空则用内置 hybrid；远程独立 solver 填 https://xxx.hf.space（TURNSTILE_SOLVER=api）",
        "restart": True,
        "simple": True,
        "placeholder": "https://your-solver.hf.space",
    },
    {
        "key": "TURNSTILE_API_TOKEN",
        "group": "turnstile",
        "type": "secret",
        "default": "",
        "label": "远程 Solver Token",
        "desc": "对接独立 turnstile-solver 仓库的 SOLVER_API_TOKEN；请求头 Bearer / X-API-Key",
        "restart": True,
        "simple": True,
    },
    {
        "key": "TURNSTILE_API_TIMEOUT",
        "group": "turnstile",
        "type": "int",
        "default": "90",
        "label": "求解超时",
        "desc": "秒",
        "restart": True,
        "simple": False,
    },
    {
        "key": "TURNSTILE_API_INFLIGHT",
        "group": "turnstile",
        "type": "int",
        "default": "0",
        "label": "同时求解数",
        "desc": "0=跟随 solver 线程数",
        "restart": True,
        "simple": False,
    },
    {
        "key": "TURNSTILE_API_POLL_INTERVAL_MS",
        "group": "turnstile",
        "type": "int",
        "default": "500",
        "label": "轮询间隔",
        "desc": "毫秒",
        "restart": True,
        "simple": False,
    },
    {
        "key": "TURNSTILE_API_MANAGED",
        "group": "turnstile",
        "type": "bool",
        "default": "1",
        "label": "允许托管 Solver",
        "desc": "允许本进程管理 hybrid/d3vin；配合「按需启动」",
        "restart": True,
        "simple": True,
    },
    {
        "key": "TURNSTILE_SOLVER_ON_DEMAND",
        "group": "turnstile",
        "type": "bool",
        "default": "1",
        "label": "按需启动 Solver",
        "desc": "默认不预启动；仅当求解失败/协议注册需要时再拉起",
        "restart": True,
        "simple": True,
    },
    {
        "key": "TURNSTILE_SOLVER_THREADS",
        "group": "turnstile",
        "type": "int",
        "default": "0",
        "label": "Solver 浏览器线程（兼容）",
        "desc": "旧名。hybrid 下 0/未设 → 走 SOLVER_GATEWAY_WORKERS=auto；仅旧版 d3vin/theyka 仍用数字线程",
        "restart": True,
        "simple": False,
    },
    {
        "key": "TURNSTILE_SOLVER_BROWSER",
        "group": "turnstile",
        "type": "choice",
        "default": "chromium",
        "label": "Solver 浏览器",
        "desc": "内置求解器用的浏览器内核",
        "restart": True,
        "simple": False,
        "options": [
            {"value": "chromium", "label": "Chromium"},
            {"value": "camoufox", "label": "Camoufox"},
        ],
    },
    {
        "key": "TURNSTILE_SOLVER_HEADLESS",
        "group": "turnstile",
        "type": "bool",
        "default": "1",
        "label": "Solver 无头模式",
        "desc": "不显示浏览器窗口",
        "restart": True,
        "simple": False,
    },
    {
        "key": "TURNSTILE_SOLVER_PROXY",
        "group": "turnstile",
        "type": "bool",
        "default": "0",
        "label": "Solver 走代理文件",
        "desc": "使用 turnstile-proxies.txt",
        "restart": True,
        "simple": False,
    },
    {
        "key": "CAPSOLVER_API_KEY",
        "group": "turnstile",
        "type": "secret",
        "default": "",
        "label": "CapSolver API Key",
        "desc": "第三方打码；有 key 时协议注册可优先走 CapSolver，减轻本机浏览器压力",
        "restart": True,
        "simple": True,
        "placeholder": "CAP-…",
    },
    {
        "key": "TWOCAPTCHA_API_KEY",
        "group": "turnstile",
        "type": "secret",
        "default": "",
        "label": "2Captcha API Key",
        "desc": "备选打码平台；与 CapSolver 二选一或作回退",
        "restart": True,
        "simple": True,
    },
    {
        "key": "TURNSTILE_SOLVER_DEBUG",
        "group": "turnstile",
        "type": "bool",
        "default": "0",
        "label": "Solver 调试日志",
        "desc": "打开详细日志",
        "restart": True,
        "simple": False,
    },
    {
        "key": "SOLVER_HARD_TIMEOUT",
        "group": "turnstile",
        "type": "int",
        "default": "90",
        "label": "本机 Solver 硬超时",
        "desc": "秒",
        "restart": True,
        "simple": False,
    },
    {
        "key": "SOLVER_REUSE",
        "group": "turnstile",
        "type": "bool",
        "default": "1",
        "label": "复用 Solver 页面",
        "desc": "减少反复开页",
        "restart": True,
        "simple": False,
    },
    {
        "key": "SOLVER_MOUSE_CLICK_RETRIES",
        "group": "turnstile",
        "type": "int",
        "default": "3",
        "label": "点击重试次数",
        "desc": "点 Turnstile 失败时重试",
        "restart": True,
        "simple": False,
    },
    # ── proxy ──
    {
        "key": "PROXY_POOL",
        "group": "proxy",
        "type": "str",
        "default": "",
        "label": "代理列表（环境变量）",
        "desc": "多代理直接写这里（HF Secrets / 面板）。支持混写多种格式，用换行或逗号/分号/| 分隔。别名 PROXY_POOL_LIST / PROXIES",
        "restart": True,
        "simple": True,
        "placeholder": "http://user:pass@1.2.3.4:8080,socks5://5.6.7.8:1080",
    },
    {
        "key": "PROXY_POOL_FILE",
        "group": "proxy",
        "type": "str",
        "default": "代理.txt",
        "label": "手动代理文件",
        "desc": "一行一个代理，默认 代理.txt；与 PROXY_POOL 合并使用",
        "restart": True,
        "simple": True,
    },
    {
        "key": "PROXY_POOL_STRATEGY",
        "group": "proxy",
        "type": "choice",
        "default": "round_robin",
        "label": "代理选取策略",
        "desc": "怎么轮换代理",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "round_robin", "label": "轮询"},
            {"value": "random", "label": "随机"},
        ],
    },
    {
        "key": "PROXY_AUTO_FETCH_ENABLED",
        "group": "proxy",
        "type": "bool",
        "default": "0",
        "label": "自动拉订阅并测活",
        "desc": "开启后从订阅源拉节点并测试",
        "restart": True,
        "simple": True,
    },
    {
        "key": "PROXY_AUTO_REQUIRE_ACTIVE",
        "group": "proxy",
        "type": "bool",
        "default": "0",
        "label": "无可用代理则停止",
        "desc": "测活一个都没有就退出，不直连",
        "restart": True,
        "simple": True,
    },
    {
        "key": "PROXY_POOL_USE_TESTED_ONLY",
        "group": "proxy",
        "type": "bool",
        "default": "0",
        "label": "只用测活通过的代理",
        "desc": "注册阶段不使用未测活节点",
        "restart": True,
        "simple": True,
    },
    {
        "key": "PROXY_AUTO_FETCH_WORKERS",
        "group": "proxy",
        "type": "int",
        "default": "8",
        "label": "拉订阅线程数",
        "desc": "并发拉订阅源",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_AUTO_TEST_WORKERS",
        "group": "proxy",
        "type": "int",
        "default": "16",
        "label": "测活线程数",
        "desc": "并发测代理",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_AUTO_MAX_ACTIVE",
        "group": "proxy",
        "type": "int",
        "default": "0",
        "label": "最多保留可用代理",
        "desc": "0=不限制",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_AUTO_MAX_CANDIDATES",
        "group": "proxy",
        "type": "int",
        "default": "0",
        "label": "单轮最多测活数",
        "desc": "0=不限制",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_WORKER_ENGINE",
        "group": "proxy",
        "type": "choice",
        "default": "go",
        "label": "测活引擎",
        "desc": "硬性栈要求 Go 二进制存在",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "go", "label": "Go（推荐）"},
            {"value": "auto", "label": "自动（有 Go 用 Go）"},
            {"value": "python", "label": "Python"},
        ],
    },
    {
        "key": "PROXY_WORKER_BIN",
        "group": "proxy",
        "type": "str",
        "default": "",
        "label": "Go 测活程序路径",
        "desc": "留空用默认 native/proxy-worker/proxy-worker",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_WORKER_URL",
        "group": "proxy",
        "type": "str",
        "default": "",
        "label": "Go 测活 HTTP 地址",
        "desc": "可选常驻服务，如 http://127.0.0.1:18765",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_RELAY_ENABLED",
        "group": "proxy",
        "type": "bool",
        "default": "1",
        "label": "分享链接中继",
        "desc": "vless/vmess 等转本地 HTTP",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PROXY_RELAY_BUILTIN_ENABLED",
        "group": "proxy",
        "type": "bool",
        "default": "1",
        "label": "内置 sing-box",
        "desc": "用内置中继处理分享链接",
        "restart": True,
        "simple": False,
    },
    {
        "key": "HTTP_PROXY",
        "group": "proxy",
        "type": "str",
        "default": "",
        "label": "全局 HTTP 代理",
        "desc": "可选，如 http://127.0.0.1:7890",
        "restart": True,
        "simple": True,
        "placeholder": "http://127.0.0.1:7890",
    },
    {
        "key": "HTTPS_PROXY",
        "group": "proxy",
        "type": "str",
        "default": "",
        "label": "全局 HTTPS 代理",
        "desc": "可选",
        "restart": True,
        "simple": True,
        "placeholder": "http://127.0.0.1:7890",
    },
    {
        "key": "PROXY_SCRAPER_OUT",
        "group": "proxy",
        "type": "str",
        "default": "logs/proxy-scraper-candidates.txt",
        "label": "爬取候选输出文件",
        "desc": "公共代理爬取结果路径",
        "restart": False,
        "simple": False,
    },
    {
        "key": "PROXY_SCRAPER_WORKERS",
        "group": "proxy",
        "type": "int",
        "default": "12",
        "label": "爬取并发",
        "desc": "拉公开代理源的并发",
        "restart": False,
        "simple": False,
    },
    {
        "key": "PROXY_SCRAPER_GITHUB",
        "group": "proxy",
        "type": "bool",
        "default": "0",
        "label": "爬取时搜 GitHub",
        "desc": "需要 GITHUB_TOKEN 更稳",
        "restart": False,
        "simple": False,
    },
    {
        "key": "PROXY_SCRAPER_AUTO_TEST",
        "group": "proxy",
        "type": "bool",
        "default": "1",
        "label": "爬取后自动测活",
        "desc": "爬完公共节点后自动启动 Go 批量测 x.ai（含中继转换）",
        "restart": False,
        "simple": True,
    },
    {
        "key": "PROXY_SCRAPER_AUTO_TEST_MAX",
        "group": "proxy",
        "type": "int",
        "default": "2000",
        "label": "自动测活最多测",
        "desc": "爬取后自动测活的候选上限",
        "restart": False,
        "simple": True,
    },
    {
        "key": "PROXY_SCRAPER_AUTO_TEST_WORKERS",
        "group": "proxy",
        "type": "int",
        "default": "128",
        "label": "自动测活并发",
        "desc": "爬取后自动测活的 Go 并发数",
        "restart": False,
        "simple": False,
    },
    {
        "key": "GITHUB_TOKEN",
        "group": "proxy",
        "type": "secret",
        "default": "",
        "label": "GitHub Token",
        "desc": "可选，提高代理源搜索配额",
        "restart": False,
        "simple": False,
    },
    # ── export ──
    {
        "key": "KEY_EXPORT_DIR",
        "group": "export",
        "type": "str",
        "default": "keys",
        "label": "导出目录",
        "desc": "账号成品输出目录",
        "restart": True,
        "simple": True,
    },
    {
        "key": "KEY_EXPORT_FORMATS",
        "group": "export",
        "type": "choice",
        "default": "legacy,sub2api",
        "label": "导出格式",
        "desc": "注册成功后写出哪些成品",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "legacy,sub2api", "label": "legacy + sub2api（推荐）"},
            {"value": "legacy,cpa", "label": "legacy + CPA"},
            {"value": "legacy,sub2api,cpa", "label": "全部：legacy + sub2api + CPA"},
            {"value": "legacy", "label": "仅 legacy（accounts.txt）"},
            {"value": "sub2api", "label": "仅 sub2api"},
            {"value": "cpa", "label": "仅 CPA"},
            {"value": "sub2api,cpa", "label": "sub2api + CPA"},
        ],
    },
    {
        "key": "KEY_EXPORT_ENROLLER",
        "group": "export",
        "type": "bool",
        "default": "1",
        "label": "自动转 OAuth",
        "desc": "SSO 自动换成 Grok OAuth 再导出",
        "restart": True,
        "simple": True,
    },
    # ── CLIProxyAPI ──
    {
        "key": "CLIPROXYAPI_ENABLED",
        "group": "cliproxyapi",
        "type": "bool",
        "default": "1",
        "label": "启用 CLIProxyAPI 同步",
        "desc": "自动把 keys/cpa/xai-*.json 单账号导入 CLIProxyAPI（不导入合并包）",
        "restart": False,
        "simple": True,
    },
    {
        "key": "CLIPROXYAPI_AUTO_IMPORT",
        "group": "cliproxyapi",
        "type": "bool",
        "default": "1",
        "label": "自动导入账号",
        "desc": "把单文件 xai-*.json 同步到 auth-dir（CLIProxyAPI 只认单账号 type=xai）",
        "restart": False,
        "simple": True,
    },
    {
        "key": "CLIPROXYAPI_AUTO_REFRESH",
        "group": "cliproxyapi",
        "type": "bool",
        "default": "1",
        "label": "过期自动刷新",
        "desc": "access_token 过期或临近过期时用 refresh_token 刷新并回写",
        "restart": False,
        "simple": True,
    },
    {
        "key": "CLIPROXYAPI_AUTH_DIR",
        "group": "cliproxyapi",
        "type": "str",
        "default": "/root/CLIProxyAPI/auths",
        "label": "CLIProxyAPI auth 目录",
        "desc": "单账号 JSON 热加载目录；不要放 accounts.cpa.json",
        "restart": False,
        "simple": True,
        "placeholder": "/root/CLIProxyAPI/auths",
    },
    {
        "key": "CLIPROXYAPI_SOURCE_DIR",
        "group": "cliproxyapi",
        "type": "str",
        "default": "keys/cpa",
        "label": "CPA 源目录",
        "desc": "本地 xai-*.json 来源（相对项目根或绝对路径）",
        "restart": False,
        "simple": False,
    },
    {
        "key": "CLIPROXYAPI_BASE_URL",
        "group": "cliproxyapi",
        "type": "str",
        "default": "http://127.0.0.1:8317",
        "label": "CLIProxyAPI 地址",
        "desc": "管理 API 基址（仅 IMPORT_VIA_API=1 时需要）",
        "restart": False,
        "simple": False,
    },
    {
        "key": "CLIPROXYAPI_MANAGEMENT_SECRET",
        "group": "cliproxyapi",
        "type": "secret",
        "default": "",
        "label": "管理密钥",
        "desc": "remote-management.secret-key / Bearer；文件复制模式可留空",
        "restart": False,
        "simple": False,
    },
    {
        "key": "CLIPROXYAPI_IMPORT_VIA_API",
        "group": "cliproxyapi",
        "type": "bool",
        "default": "0",
        "label": "走管理 API 导入",
        "desc": "0=复制到 auth-dir（推荐）；1=POST /v0/management/auth-files",
        "restart": False,
        "simple": False,
    },
    {
        "key": "CLIPROXYAPI_INTERVAL_SEC",
        "group": "cliproxyapi",
        "type": "int",
        "default": "300",
        "label": "同步间隔秒",
        "desc": "后台 worker 刷新+导入周期",
        "restart": False,
        "simple": True,
    },
    {
        "key": "CLIPROXYAPI_REFRESH_LEAD_SEC",
        "group": "cliproxyapi",
        "type": "int",
        "default": "300",
        "label": "提前刷新秒数",
        "desc": "距 expired 还有多少秒开始刷新（默认 5 分钟）",
        "restart": False,
        "simple": False,
    },
    {
        "key": "CLIPROXYAPI_PREFER_GROK_CLI_BASE",
        "group": "cliproxyapi",
        "type": "bool",
        "default": "1",
        "label": "优先 Grok CLI 通道",
        "desc": "base_url 用 cli-chat-proxy.grok.com，避免 api.x.ai 402",
        "restart": False,
        "simple": True,
    },
    {
        "key": "CLIPROXYAPI_REMOVE_BUNDLES",
        "group": "cliproxyapi",
        "type": "bool",
        "default": "1",
        "label": "清理合并包",
        "desc": "从 auth-dir 删除 accounts.cpa*.json（CLIProxyAPI 不识别）",
        "restart": False,
        "simple": False,
    },
    # ── cf-ares ──
    {
        "key": "CF_ARES_EMAIL",
        "group": "cf_ares",
        "type": "choice",
        "default": "0",
        "label": "邮箱走 CF-Ares",
        "desc": "邮箱 HTTP 是否过 CF-Ares",
        "restart": True,
        "simple": False,
        "options": [
            {"value": "0", "label": "关闭"},
            {"value": "fallback", "label": "失败时回退"},
            {"value": "always", "label": "始终"},
        ],
    },
    {
        "key": "CF_ARES_XAI",
        "group": "cf_ares",
        "type": "choice",
        "default": "",
        "label": "xAI 走 CF-Ares",
        "desc": "留空=跟随默认策略",
        "restart": True,
        "simple": False,
        "options": [
            {"value": "", "label": "默认"},
            {"value": "0", "label": "关闭"},
            {"value": "fallback", "label": "失败时回退"},
            {"value": "always", "label": "始终"},
        ],
    },
    {
        "key": "CF_ARES_HEADLESS",
        "group": "cf_ares",
        "type": "bool",
        "default": "1",
        "label": "CF-Ares 无头",
        "desc": "无界面运行",
        "restart": True,
        "simple": False,
    },
    {
        "key": "CF_ARES_BROWSER_ENGINE",
        "group": "cf_ares",
        "type": "str",
        "default": "auto",
        "label": "CF-Ares 浏览器引擎",
        "desc": "auto / undetected 等",
        "restart": True,
        "simple": False,
    },
    # ── runtime / dashboard ──
    {
        "key": "REGISTER_LOG_MODE",
        "group": "runtime",
        "type": "choice",
        "default": "user",
        "label": "日志模式",
        "desc": "user 简洁 / debug 详细",
        "restart": True,
        "simple": True,
        "options": [
            {"value": "user", "label": "简洁（用户）"},
            {"value": "debug", "label": "调试（debug）"},
        ],
    },
    {
        "key": "REGISTER_HEARTBEAT_INTERVAL",
        "group": "runtime",
        "type": "int",
        "default": "60",
        "label": "心跳间隔",
        "desc": "秒",
        "restart": True,
        "simple": False,
    },
    {
        "key": "REGISTRATION_RATE_LIMIT_COOLDOWN",
        "group": "runtime",
        "type": "int",
        "default": "60",
        "label": "限流冷却",
        "desc": "被限流后等待秒数",
        "restart": True,
        "simple": True,
    },
    {
        "key": "C_HOT_PAGE_POOL",
        "group": "runtime",
        "type": "bool",
        "default": "0",
        "label": "复用注册页",
        "desc": "热页面池，可能提升速度",
        "restart": True,
        "simple": False,
    },
    {
        "key": "C_SET_COOKIE_VIA_REQUEST",
        "group": "runtime",
        "type": "bool",
        "default": "1",
        "label": "用 request 写 Cookie",
        "desc": "注册路径写 cookie 方式",
        "restart": True,
        "simple": False,
    },
    {
        "key": "PAGE_BLOCK_STATIC_ASSETS",
        "group": "runtime",
        "type": "bool",
        "default": "0",
        "label": "阻断静态资源",
        "desc": "省带宽，可能影响页面",
        "restart": True,
        "simple": False,
    },
    {
        "key": "DASHBOARD_HOST",
        "group": "dashboard",
        "type": "str",
        "default": "127.0.0.1",
        "label": "面板监听地址",
        "desc": "改 0.0.0.0 可局域网访问（注意安全）",
        "restart": False,
        "simple": False,
    },
    {
        "key": "DASHBOARD_PORT",
        "group": "dashboard",
        "type": "int",
        "default": "8787",
        "label": "面板端口",
        "desc": "默认 8787",
        "restart": False,
        "simple": False,
    },
    {
        "key": "CONTROL_PLANE_ALLOW_ACTIONS",
        "group": "dashboard",
        "type": "bool",
        "default": "0",
        "label": "允许面板操作",
        "desc": "开启后可在面板启停注册、保存配置、爬代理",
        "restart": False,
        "simple": True,
    },
    {
        "key": "AUTO_START_REGISTER",
        "group": "dashboard",
        "type": "bool",
        "default": "0",
        "label": "面板启动时自动注册",
        "desc": "1=容器/面板起来后自动跑 REGISTER_ENGINE（HF 默认开）。不依赖点「启动」按钮",
        "restart": True,
        "simple": True,
    },
    {
        "key": "AUTO_RESTART_REGISTER",
        "group": "dashboard",
        "type": "bool",
        "default": "0",
        "label": "注册退出后自动拉起",
        "desc": "1=注册进程挂了后由面板监督线程再启动（配合 AUTO_START_REGISTER）",
        "restart": True,
        "simple": True,
    },
    {
        "key": "AUTO_START_DELAY_SEC",
        "group": "dashboard",
        "type": "int",
        "default": "3",
        "label": "自动启动延迟秒",
        "desc": "等面板 /health 先就绪再 spawn 注册，避免 HF 探针超时",
        "restart": True,
        "simple": False,
    },
    {
        "key": "DASHBOARD_USER",
        "group": "dashboard",
        "type": "str",
        "default": "admin",
        "label": "面板登录用户名",
        "desc": "HTTP Basic 用户名；需同时设置 DASHBOARD_PASSWORD",
        "restart": True,
        "simple": True,
    },
    {
        "key": "DASHBOARD_PASSWORD",
        "group": "dashboard",
        "type": "secret",
        "default": "",
        "label": "面板登录密码",
        "desc": "非空则启用 HTTP Basic；公网/HF Space 务必设置。别名 CONTROL_PLANE_PASSWORD",
        "restart": True,
        "simple": True,
    },
    {
        "key": "CONTROL_PLANE_TOKEN",
        "group": "dashboard",
        "type": "secret",
        "default": "",
        "label": "面板 API Token",
        "desc": "可选 Bearer / X-API-Key；与密码二选一或同时启用。别名 DASHBOARD_TOKEN",
        "restart": True,
        "simple": True,
    },
    {
        "key": "DASHBOARD_LANG",
        "group": "dashboard",
        "type": "choice",
        "default": "zh",
        "label": "面板默认语言",
        "desc": "zh 中文 / en 英文（浏览器也会记住你的切换）",
        "restart": False,
        "simple": True,
        "options": [
            {"value": "zh", "label": "中文"},
            {"value": "en", "label": "English"},
        ],
    },
]

GROUPS = [
    ("email", "邮箱"),
    ("capacity", "并发与容量"),
    ("turnstile", "Turnstile 过盾"),
    ("proxy", "代理与爬取"),
    ("export", "导出成品"),
    ("cliproxyapi", "CLIProxyAPI"),
    ("cf_ares", "CF-Ares"),
    ("runtime", "运行时"),
    ("dashboard", "控制面板"),
]

# 常用配置键顺序（面板「常用」视图）
SIMPLE_KEYS = [
    "EMAIL_MODE",
    "MOEMAIL_API_KEY",
    "MOEMAIL_API",
    "EMAIL_DOMAIN",
    "EMAIL_API",
    "TARGET",
    "PHYSICAL_CAP",
    "REGISTER_ENGINE",
    "TURNSTILE_SOLVER",
    "SOLVER_GATEWAY_WORKERS",
    "SOLVER_GATEWAY_WORKERS_MAX",
    "SOLVER_WORKER_CONCURRENCY",
    "SOLVER_WATCHDOG_SOFT_MB",
    "SOLVER_WATCHDOG_HARD_MB",
    "TURNSTILE_SOLVER_THREADS",
    "TURNSTILE_API_MANAGED",
    "TURNSTILE_API_URL",
    "PROXY_POOL",
    "PROXY_POOL_FILE",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "PROXY_AUTO_FETCH_ENABLED",
    "PROXY_AUTO_REQUIRE_ACTIVE",
    "PROXY_POOL_USE_TESTED_ONLY",
    "CLIPROXYAPI_ENABLED",
    "CLIPROXYAPI_AUTO_IMPORT",
    "CLIPROXYAPI_AUTO_REFRESH",
    "CLIPROXYAPI_AUTH_DIR",
    "CLIPROXYAPI_INTERVAL_SEC",
    "CLIPROXYAPI_PREFER_GROK_CLI_BASE",
    "PROXY_WORKER_ENGINE",
    "PROXY_POOL_STRATEGY",
    "KEY_EXPORT_FORMATS",
    "KEY_EXPORT_DIR",
    "KEY_EXPORT_ENROLLER",
    "INVENTORY_ENGINE",
    "REGISTER_LOG_MODE",
    "REGISTRATION_RATE_LIMIT_COOLDOWN",
    "CONTROL_PLANE_ALLOW_ACTIONS",
    "AUTO_START_REGISTER",
    "AUTO_RESTART_REGISTER",
    "DASHBOARD_USER",
    "DASHBOARD_PASSWORD",
    "CONTROL_PLANE_TOKEN",
    "DASHBOARD_LANG",
    "CAPSOLVER_API_KEY",
    "TWOCAPTCHA_API_KEY",
]

SECRET_KEYS = {e["key"] for e in CATALOG if e.get("type") == "secret"}
CATALOG_BY_KEY = {e["key"]: e for e in CATALOG}

# One-click env presets for environments without shell access (HF Space / Docker)
CONFIG_PRESETS: dict[str, dict[str, Any]] = {
    "hf_protocol": {
        "label": "HF / Docker · 协议注册",
        "desc": "协议引擎 + 新版 hybrid Turnstile（auto 并发）",
        "env": {
            "REGISTER_ENGINE": "protocol",
            "TURNSTILE_SOLVER": "hybrid",
            "TURNSTILE_SOLVER_ON_DEMAND": "1",
            "TURNSTILE_SOLVER_HEADLESS": "1",
            "SOLVER_GATEWAY_WORKERS": "auto",
            "SOLVER_GATEWAY_WORKERS_MAX": "8",
            "SOLVER_WORKER_CONCURRENCY": "0",
            "TURNSTILE_API_URL": "http://127.0.0.1:5080",
            "GO_REGISTER_WORKERS": "8",
            "CONTROL_PLANE_ALLOW_ACTIONS": "1",
            "KEY_EXPORT_DIR": "/data/keys",
        },
    },
    "hf_capsolver": {
        "label": "HF · 协议 + CapSolver",
        "desc": "有 CAPSOLVER_API_KEY 时优先打码 API；hybrid auto 作回退",
        "env": {
            "REGISTER_ENGINE": "protocol",
            "TURNSTILE_SOLVER": "hybrid",
            "TURNSTILE_SOLVER_ON_DEMAND": "1",
            "SOLVER_GATEWAY_WORKERS": "auto",
            "GO_REGISTER_WORKERS": "8",
            "CONTROL_PLANE_ALLOW_ACTIONS": "1",
        },
    },
    "local_fast": {
        "label": "本机高速协议",
        "desc": "8 协议 worker + hybrid auto 浏览器",
        "env": {
            "REGISTER_ENGINE": "protocol",
            "TURNSTILE_SOLVER": "hybrid",
            "TURNSTILE_SOLVER_ON_DEMAND": "1",
            "SOLVER_GATEWAY_WORKERS": "auto",
            "SOLVER_GATEWAY_WORKERS_MAX": "8",
            "GO_REGISTER_WORKERS": "8",
            "CONTROL_PLANE_ALLOW_ACTIONS": "1",
        },
    },
    "browser_python": {
        "label": "浏览器注册路径",
        "desc": "REGISTER_ENGINE=python（Playwright 全流程）",
        "env": {
            "REGISTER_ENGINE": "python",
            "TURNSTILE_SOLVER": "local",
            "CONTROL_PLANE_ALLOW_ACTIONS": "1",
        },
    },
    "safe_readonly": {
        "label": "只读面板",
        "desc": "禁止面板启停操作（仅查看）",
        "env": {
            "CONTROL_PLANE_ALLOW_ACTIONS": "0",
        },
    },
    "moemail_setup": {
        "label": "MoeMail 邮箱",
        "desc": "切到 MoeMail OpenAPI（仍需自行填 MOEMAIL_API_KEY）",
        "env": {
            "EMAIL_MODE": "moemail",
            "MOEMAIL_API": "https://moemail.app",
            "CONTROL_PLANE_ALLOW_ACTIONS": "1",
        },
    },
    "tempmail_free": {
        "label": "免费临时邮箱",
        "desc": "EMAIL_MODE=tempmail，零配置收码",
        "env": {
            "EMAIL_MODE": "tempmail",
            "CONTROL_PLANE_ALLOW_ACTIONS": "1",
        },
    },
    "export_all_formats": {
        "label": "全格式导出",
        "desc": "legacy + sub2api + cpa 同时写出",
        "env": {
            "KEY_EXPORT_FORMATS": "legacy,sub2api,cpa",
            "KEY_EXPORT_ENROLLER": "1",
        },
    },
}


def catalog_public() -> list[dict[str, Any]]:
    return list(CATALOG)


def presets_public() -> list[dict[str, Any]]:
    out = []
    for pid, meta in CONFIG_PRESETS.items():
        out.append(
            {
                "id": pid,
                "label": meta.get("label") or pid,
                "desc": meta.get("desc") or "",
                "keys": list((meta.get("env") or {}).keys()),
            }
        )
    return out


def mask_secret(value: str) -> str:
    if not value:
        return ""
    if len(value) <= 6:
        return "*" * len(value)
    return value[:3] + "*" * (len(value) - 6) + value[-3:]
